import type { Character } from "../domain/character";
import { VERIFIED_PDF_CHARACTERS } from "./verified-pdf-characters";

export const cleiraOestwilde: Character = {
  id: "cleira-oestwilde",
  name: "Cleira Oestwilde",
  className: "Bard",
  level: 1,
  rulesetId: "dnd-2014",
  armorClass: 13,
  speedFeet: 30,
  hitPoints: { current: 10, maximum: 10 },
  proficiencyBonus: 2,
  abilities: { strength: 8, dexterity: 15, constitution: 14, intelligence: 13, wisdom: 10, charisma: 15 },
  savingThrowModifiers: { strength: -1, dexterity: 4, constitution: 2, intelligence: 1, wisdom: 0, charisma: 4 },
  resources: [
    { id: "bardic-inspiration", name: "Bardic Inspiration", kind: "generic", current: 2, maximum: 2, recovery: "long-rest" },
    { id: "spell-slot-1", name: "Level 1 Spell Slots", kind: "spell-slot", level: 1, current: 2, maximum: 2, recovery: "long-rest" },
  ],
  passiveFeatures: [{
    id: "fey-ancestry",
    name: "Fey Ancestry",
    description: "Advantage on saving throws against being charmed; magic cannot put Cleira to sleep.",
    resolution: { type: "ancestry-defense", savingThrowAdvantageAgainstConditions: ["charmed"], conditionImmunities: ["magical sleep"] },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Elf: Fey Ancestry" },
  }, {
    id: "keen-senses",
    name: "Keen Senses",
    description: "Proficiency in the Perception skill applies to Perception ability checks.",
    resolution: { type: "skill-proficiency", skill: "Perception", ability: "wisdom" },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Elf: Keen Senses" },
  }, {
    id: "trance",
    name: "Trance",
    description: "Cleira does not need to sleep and instead meditates semiconsciously for 4 hours each day.",
    resolution: { type: "rest-alternative", sleepRequired: false, meditationHours: 4, semiconscious: true },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Elf: Trance" },
  }],
  featureActions: [{
    id: "bardic-inspiration",
    name: "Bardic Inspiration",
    cost: "bonus-action",
    description: "Grant another creature within 60 feet that can hear Cleira one d6 to add to one ability check, attack roll, or saving throw within 10 minutes.",
    resourceName: "Bardic Inspiration",
    resourceCost: 1,
    resolution: { type: "grant-roll-bonus", rangeFeet: 60, excludesSelf: true, requiresHearing: true, die: "1d6", appliesTo: ["ability-check", "attack-roll", "saving-throw"], durationRounds: 100 },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Bard: Bardic Inspiration" },
  }],
  equipmentRules: [{
    id: "leather-armor",
    name: "Leather Armor",
    equipped: true,
    description: "Light armor that sets AC to 11 plus the wearer’s Dexterity modifier.",
    resolution: { type: "armor", category: "light", baseArmorClass: 11, dexterityModifier: "full" },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Armor and Shields: Leather" },
  }, {
    id: "dagger",
    name: "Dagger",
    equipped: true,
    description: "One carried dagger supports both melee attacks and thrown attacks; throwing it removes that copy from carried inventory.",
    resolution: { type: "weapon", attackIds: ["dagger", "thrown-dagger"], expendOnAttackIds: ["thrown-dagger"] },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Weapons: Dagger and Thrown" },
  }, {
    id: "rapier",
    name: "Rapier",
    equipped: true,
    description: "A carried rapier enables Cleira's registered melee attack.",
    resolution: { type: "weapon", attackIds: ["rapier"] },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Weapons: Rapier" },
  }, {
    id: "lute",
    name: "Lute",
    equipped: true,
    description: "A musical instrument Cleira can use as a spellcasting focus for bard spells.",
    resolution: { type: "spellcasting-focus", spellcastingClass: "Bard" },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Bard: Spellcasting Focus" },
  }, {
    id: "disguise-kit",
    name: "Disguise Kit",
    equipped: true,
    description: "Use the carried kit to make an ability check while creating a visual disguise; tool proficiency adds the proficiency bonus when present.",
    resolution: { type: "tool-check", purpose: "create a visual disguise", allowedAbilities: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"], actionCost: "action" },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Tools: Disguise Kit" },
  }],
  attacks: [
    { id: "rapier", name: "Rapier", kind: "melee", attackBonus: 4, damage: "1d8 + 2 piercing", normalRangeFeet: 5, description: "Martial, finesse, Vex." },
    { id: "dagger", name: "Dagger", kind: "melee", attackBonus: 4, damage: "1d4 + 2 piercing", normalRangeFeet: 5, description: "Simple, finesse, light." },
    { id: "thrown-dagger", name: "Thrown Dagger", kind: "ranged", attackBonus: 4, damage: "1d4 + 2 piercing", normalRangeFeet: 20, longRangeFeet: 60, description: "Normal to 20 feet; disadvantage from 25 to 60 feet." },
    { id: "unarmed-strike", name: "Unarmed Strike", kind: "melee", attackBonus: 1, damage: "0 bludgeoning", normalRangeFeet: 5, description: "Fixed damage shown on the source sheet." },
  ],
  spells: [
    { id: "dancing-lights", name: "Dancing Lights", level: 0, castingTime: "action", rangeFeet: 120, target: "point", requiresLineOfSight: true, concentration: true, durationRounds: 10, description: "Creates up to four movable lights that each cast dim light in a 10-foot radius for 1 minute.", pointEffect: { type: "lights", maximumPoints: 4, dimLightFeet: 10, movementFeet: 60 }, provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Dancing Lights" } },
    { id: "vicious-mockery", name: "Vicious Mockery", level: 0, castingTime: "action", rangeFeet: 60, target: "single", targetSide: "hostile", requiresLineOfSight: true, requiresTargetHearing: true, damage: "1d4 psychic", save: { ability: "wisdom", dc: 12, damageOnSuccess: "none" }, description: "The target makes a DC 12 Wisdom save; on a failure it takes psychic damage and has disadvantage on its next attack roll before the end of its next turn.", effect: { name: "Vicious Mockery", description: "Disadvantage on the next attack roll before the end of this creature's next turn.", modifiers: { outgoingAttacks: "disadvantage" }, expires: "end-of-target-next-turn", consumeOnAttackRoll: true }, provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Vicious Mockery" } },
    { id: "minor-illusion", name: "Minor Illusion", level: 0, castingTime: "action", rangeFeet: 30, target: "point", requiresLineOfSight: true, durationRounds: 10, description: "Create either a sound or a visual image of an object at a point within 30 feet for 1 minute.", utilityChoices: [
      { id: "sound", name: "Create sound", description: "Place a sound at the chosen point for the spell's duration.", resolution: { type: "illusion", mode: "sound", sizeFeet: 5 } },
      { id: "image", name: "Create image", description: "Place an image of an object no larger than one 5-foot cube.", resolution: { type: "illusion", mode: "image", sizeFeet: 5 } },
    ], provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Minor Illusion" } },
    { id: "charm-person", name: "Charm Person", level: 1, castingTime: "action", rangeFeet: 30, target: "single", targetSide: "hostile", requiresLineOfSight: true, save: { ability: "wisdom", dc: 12, damageOnSuccess: "none" }, targetCreatureTypes: ["humanoid"], hostileSaveAdvantage: true, durationRounds: 600, missingCapabilities: ["Social-interaction advantage, friendly targeting, and explicit fighting relationships are not yet modeled."], description: "A humanoid target makes a DC 12 Wisdom save with advantage while fighting the caster or an ally. On a failure, it is charmed for 1 hour or until harmed by the caster or an ally.", effect: { name: "Charm Person", description: "The target is charmed by the caster and cannot harm the caster until the spell ends.", conditionGranted: "charmed", modifiers: { preventsHarmingSource: true }, endsWhenSourceHarmsTarget: true, revealsSourceOnEnd: true }, provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Charm Person" } },
    { id: "detect-magic", name: "Detect Magic", level: 1, castingTime: "action", rangeFeet: 0, target: "self", requiresLineOfSight: false, ritual: true, concentration: true, durationRounds: 100, description: "Senses registered magic within 30 feet and supports an Action to reveal visible auras and schools.", missingCapabilities: ["Barrier material and thickness, and schools for spell-effect auras, are not yet modeled.", "Ten-minute ritual casting is recorded but not executable during combat."], provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Detect Magic" }, effect: { name: "Detect Magic", description: "Cleira senses whether registered magic is present within 30 feet.", senseMagic: { rangeFeet: 30, blockedByTotalCover: true } } },
    { id: "healing-word", name: "Healing Word", level: 1, castingTime: "bonus-action", rangeFeet: 60, target: "self-or-single", targetSide: "friendly", requiresLineOfSight: true, healing: "1d4 + 2 healing", description: "A visible creature within 60 feet regains 1d4 + 2 hit points." },
    { id: "thunderwave", name: "Thunderwave", level: 1, castingTime: "action", rangeFeet: 0, target: "area", targetSide: "hostile", requiresLineOfSight: false, damage: "2d8 thunder", save: { ability: "constitution", dc: 12, damageOnSuccess: "half" }, area: { origin: "self", shape: "cube", sizeFeet: 15, affects: "all-creatures", pushFeetOnFailedSave: 10 }, description: "Aim a 15-foot cube through a selected creature. Each creature in it saves; failures are pushed, and the boom is recorded as audible to 300 feet.", missingCapabilities: ["Unsecured objects are reported as affected, but the current maps do not track movable loose objects."], provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Thunderwave" } },
  ],
  actions: ["Attack", "Cast a Spell", "Dash", "Disengage", "Dodge", "Help", "Hide", "Ready", "Search", "Use an Object"],
  profile: {
    playerName: "ChefdeStruct",
    species: "High Elf",
    background: "Smuggler",
    alignment: "Chaotic Neutral",
    initiativeModifier: 2,
    spellcasting: { ability: "charisma", saveDc: 12, attackBonus: 4 },
    senses: { darkvisionFeet: 60, passivePerception: 12, passiveInsight: 10, passiveInvestigation: 11 },
    skills: { Acrobatics: 4, "Animal Handling": 0, Arcana: 1, Athletics: 1, Deception: 4, History: 1, Insight: 0, Intimidation: 2, Investigation: 1, Medicine: 0, Nature: 1, Perception: 2, Performance: 4, Persuasion: 2, Religion: 1, "Sleight of Hand": 4, Stealth: 2, Survival: 0 },
    proficiencies: {
      armor: ["Light Armor"],
      weapons: ["Hand Crossbow", "Longbow", "Longsword", "Rapier", "Shortsword", "Simple Weapons"],
      tools: ["Flute", "Lute", "Vehicles (Water)", "Viol"],
      languages: ["Celestial", "Common", "Elvish"],
    },
    equipment: [
      { name: "Leather Armor", quantity: 1, weightPounds: 10 },
      { name: "Dagger", quantity: 1, weightPounds: 1 },
      { name: "Rapier", quantity: 1, weightPounds: 2 },
      { name: "Lute", quantity: 1, weightPounds: 2 },
      { name: "Disguise Kit", quantity: 1, weightPounds: 3 },
    ],
    features: [
      { id: "bardic-inspiration", name: "Bardic Inspiration", description: "Twice per long rest, grant another creature within 60 feet a d6 inspiration die as a bonus action.", executableActionId: "bardic-inspiration", provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Bard: Bardic Inspiration" } },
      { id: "fey-ancestry", name: "Fey Ancestry", description: "Advantage on saving throws against being charmed; magic cannot put Cleira to sleep.", executablePassiveId: "fey-ancestry", provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Elf: Fey Ancestry" } },
      { id: "trance", name: "Trance", description: "Does not need sleep and meditates semiconsciously for 4 hours each day.", executablePassiveId: "trance", provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Elf: Trance" } },
      { id: "keen-senses", name: "Keen Senses", description: "Proficient in Perception.", executablePassiveId: "keen-senses", provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Elf: Keen Senses" } },
    ],
  },
  source: { format: "flattened-pdf", fileName: "ChefdeStruct_170365689.pdf", importedAt: "2026-08-29T02:24:02.000Z" },
};

export const BUILT_IN_CHARACTERS: Character[] = [cleiraOestwilde, ...VERIFIED_PDF_CHARACTERS];
