import type { Character } from "../domain/character";

const standardActions2014 = ["Attack", "Cast a Spell", "Dash", "Disengage", "Dodge", "Help", "Hide", "Ready", "Search", "Use an Object"];
const standardActions2024 = ["Attack", "Magic", "Dash", "Disengage", "Dodge", "Help", "Hide", "Ready", "Search", "Utilize", "Study", "Influence"];
const importedAt = "2026-08-31T00:00:00.000Z";

export const surinaDaardendrian: Character = {
  id: "surina-daardendrian",
  name: "Surina Daardendrian",
  className: "Paladin",
  level: 1,
  rulesetId: "dnd-2014",
  armorClass: 16,
  speedFeet: 30,
  hitPoints: { current: 11, maximum: 11 },
  proficiencyBonus: 2,
  abilities: { strength: 17, dexterity: 8, constitution: 13, intelligence: 12, wisdom: 10, charisma: 15 },
  savingThrowModifiers: { strength: 3, dexterity: -1, constitution: 1, intelligence: 1, wisdom: 2, charisma: 4 },
  resources: [
    { id: "breath-weapon-gold", name: "Breath Weapon (Gold)", kind: "generic", current: 1, maximum: 1, recovery: "short-rest" },
    { id: "divine-sense", name: "Divine Sense", kind: "generic", current: 3, maximum: 3, recovery: "long-rest" },
    { id: "lay-on-hands", name: "Lay on Hands Pool", kind: "generic", current: 5, maximum: 5, recovery: "long-rest" },
  ],
  passiveFeatures: [{
    id: "fire-resistance",
    name: "Fire Resistance",
    description: "Gold Dragon ancestry grants resistance to fire damage.",
    resolution: { type: "damage-resistance", damageTypes: ["fire"] },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Dragonborn: Damage Resistance" },
  }],
  featureActions: [{
    id: "divine-sense",
    name: "Divine Sense",
    cost: "action",
    description: "Until the end of the next turn, sense celestials, fiends, and undead within 60 feet that are not behind total cover, plus consecrated or desecrated presence.",
    resourceName: "Divine Sense",
    resourceCost: 1,
    resolution: { type: "sense-creature-types", creatureTypes: ["celestial", "fiend", "undead"], rangeFeet: 60, duration: "end-of-next-turn", blockedByTotalCover: true },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Paladin: Divine Sense" },
  }, {
    id: "lay-on-hands",
    name: "Lay on Hands",
    cost: "action",
    description: "As an Action, touch yourself or an ally and choose how many Lay on Hands points to spend as Hit Point healing.",
    resourceName: "Lay on Hands Pool",
    resourceCost: "variable",
    resolution: { type: "healing-pool", rangeFeet: 5 },
    missingCapabilities: ["Disease curing, poison neutralization, and undead or construct target validation are not executable yet."],
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Paladin: Lay on Hands" },
  }],
  attacks: [
    { id: "glaive", name: "Glaive", kind: "melee", attackBonus: 5, damage: "1d10 + 3 slashing", normalRangeFeet: 10, description: "Martial, heavy, reach, two-handed, Graze." },
    { id: "longsword", name: "Longsword", kind: "melee", attackBonus: 5, damage: "1d8 + 3 slashing", normalRangeFeet: 5, description: "Carried martial weapon; one-handed damage." },
    { id: "javelin", name: "Javelin", kind: "melee", attackBonus: 5, damage: "1d6 + 3 piercing", normalRangeFeet: 5, description: "Carried simple melee weapon." },
    { id: "thrown-javelin", name: "Thrown Javelin", kind: "ranged", attackBonus: 5, damage: "1d6 + 3 piercing", normalRangeFeet: 30, longRangeFeet: 120, description: "Normal to 30 feet; disadvantage from 35 to 120 feet." },
    { id: "unarmed-strike", name: "Unarmed Strike", kind: "melee", attackBonus: 5, damage: "4 bludgeoning", normalRangeFeet: 5, description: "Fixed damage shown on the source sheet." },
  ],
  actions: standardActions2014,
  profile: {
    playerName: "ChefdeStruct",
    species: "Dragonborn",
    background: "Noble",
    alignment: "Lawful Good",
    initiativeModifier: -1,
    senses: { passivePerception: 10, passiveInsight: 10, passiveInvestigation: 11 },
    skills: { Acrobatics: -1, "Animal Handling": 0, Arcana: 1, Athletics: 5, Deception: 2, History: 3, Insight: 0, Intimidation: 2, Investigation: 1, Medicine: 0, Nature: 1, Perception: 0, Performance: 2, Persuasion: 4, Religion: 3, "Sleight of Hand": -1, Stealth: -1, Survival: 0 },
    proficiencies: { armor: ["Heavy Armor", "Light Armor", "Medium Armor", "Shields"], weapons: ["Martial Weapons", "Simple Weapons"], tools: ["Dragonchess Set"], languages: ["Common", "Draconic", "Dwarvish"] },
    equipment: [
      { name: "Chain Mail", quantity: 1, weightPounds: 55 },
      { name: "Glaive", quantity: 1, weightPounds: 6 },
      { name: "Longsword", quantity: 1, weightPounds: 3 },
      { name: "Javelin", quantity: 5, weightPounds: 2 },
    ],
    features: [
      { id: "fire-resistance", name: "Fire Resistance", description: "Resistance to fire damage from Gold Dragon ancestry.", executablePassiveId: "fire-resistance", provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Dragonborn: Damage Resistance" } },
      { name: "Breath Weapon (Gold)", description: "Once per short rest, creatures in a 15-foot cone make a DC 11 Dexterity save; 2d6 fire damage on a failure and half on a success. Area targeting is not implemented yet." },
      { id: "divine-sense", name: "Divine Sense", description: "Three times per long rest, sense certain celestials, fiends, undead, and hallowed places within 60 feet until the end of the next turn.", executableActionId: "divine-sense", provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Paladin: Divine Sense" } },
      { id: "lay-on-hands", name: "Lay on Hands", description: "Spend points from a 5-point pool as an Action to heal by touch, or spend 5 points to cure one disease or neutralize one poison.", executableActionId: "lay-on-hands", provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Paladin: Lay on Hands" } },
    ],
  },
  source: { format: "flattened-pdf", fileName: "Dragonborn Paladin.pdf", importedAt },
};

export const goliathBarbarian: Character = {
  id: "goliath-barbarian",
  name: "Goliath Barbarian",
  className: "Barbarian",
  level: 1,
  rulesetId: "dnd-2024",
  armorClass: 13,
  speedFeet: 35,
  hitPoints: { current: 14, maximum: 14 },
  proficiencyBonus: 2,
  abilities: { strength: 15, dexterity: 12, constitution: 14, intelligence: 8, wisdom: 13, charisma: 10 },
  savingThrowModifiers: { strength: 4, dexterity: 1, constitution: 4, intelligence: -1, wisdom: 1, charisma: 0 },
  resources: [
    { id: "rage", name: "Rage", kind: "generic", current: 2, maximum: 2, recovery: "special", shortRestRecovery: 1, longRestRecovery: "all" },
    { id: "stones-endurance", name: "Stone's Endurance", kind: "generic", current: 2, maximum: 2, recovery: "long-rest" },
    { id: "large-form", name: "Large Form", kind: "generic", current: 1, maximum: 1, recovery: "long-rest" },
  ],
  passiveFeatures: [{
    id: "unarmored-defense",
    name: "Unarmored Defense",
    description: "While not wearing armor, base AC equals 10 plus Dexterity and Constitution modifiers; a shield can still apply.",
    resolution: { type: "unarmored-defense", abilityModifiers: ["dexterity", "constitution"], allowsShield: true },
    provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Barbarian: Unarmored Defense" },
  }],
  featureActions: [{
    id: "rage",
    name: "Rage",
    cost: "bonus-action",
    description: "As a Bonus Action, expend one Rage use to gain resistance to bludgeoning, piercing, and slashing damage until the end of your next turn.",
    resourceName: "Rage",
    resourceCost: 1,
    resolution: {
      type: "activate-effect",
      effect: {
        name: "Rage",
        description: "Resistance to bludgeoning, piercing, and slashing damage.",
        duration: "end-of-next-turn",
        modifiers: { damageResistances: ["bludgeoning", "piercing", "slashing"] },
      },
    },
    missingCapabilities: ["Rage Damage, Strength Advantage, duration extension, and early-ending conditions are not executable yet."],
    provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Barbarian: Rage" },
  }],
  triggeredFeatures: [{
    id: "stones-endurance",
    name: "Stone's Endurance",
    trigger: "takes-damage",
    optional: true,
    description: "After taking damage, use a Reaction and spend one use to reduce that damage by 1d12 + 2.",
    resourceName: "Stone's Endurance",
    resourceCost: 1,
    resolution: { type: "reduce-damage-by-roll", die: "1d12", modifier: 2 },
    provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Goliath: Giant Ancestry (Stone's Endurance)" },
  }],
  attacks: [
    { id: "maul", name: "Maul", kind: "melee", attackBonus: 4, damage: "2d6 + 2 bludgeoning", normalRangeFeet: 5, description: "Martial, heavy, two-handed, Topple." },
    { id: "spear", name: "Spear", kind: "melee", attackBonus: 4, damage: "1d6 + 2 piercing", normalRangeFeet: 5, description: "Simple, versatile, Sap; one-handed damage." },
    { id: "thrown-spear", name: "Thrown Spear", kind: "ranged", attackBonus: 4, damage: "1d6 + 2 piercing", normalRangeFeet: 20, longRangeFeet: 60, description: "Normal to 20 feet; disadvantage from 25 to 60 feet." },
    { id: "unarmed-strike", name: "Unarmed Strike", kind: "melee", attackBonus: 4, damage: "3 bludgeoning", normalRangeFeet: 5, description: "Fixed damage shown on the source sheet." },
  ],
  actions: standardActions2024,
  profile: {
    playerName: "ChefdeStruct",
    species: "Goliath",
    background: "Soldier",
    initiativeModifier: 1,
    senses: { passivePerception: 11, passiveInsight: 11, passiveInvestigation: 9 },
    skills: { Acrobatics: 1, "Animal Handling": 1, Arcana: -1, Athletics: 4, Deception: 0, History: -1, Insight: 1, Intimidation: 2, Investigation: -1, Medicine: 1, Nature: 1, Perception: 1, Performance: 0, Persuasion: 0, Religion: -1, "Sleight of Hand": 1, Stealth: 1, Survival: 3 },
    proficiencies: { armor: ["Light Armor", "Medium Armor", "Shields"], weapons: ["Martial Weapons", "Simple Weapons"], tools: ["Darts"], languages: ["Common", "Giant", "Orc"] },
    equipment: [{ name: "Spear", quantity: 5, weightPounds: 3 }, { name: "Maul", quantity: 1, weightPounds: 10 }, { name: "Hooded Lantern", quantity: 1, weightPounds: 2 }],
    features: [
      { id: "rage", name: "Rage", description: "Enter Rage as a Bonus Action. Damage resistance and the initial duration are executable; Rage Damage, Strength Advantage, duration extension, and early-ending conditions are not implemented yet.", executableActionId: "rage", provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Barbarian: Rage" } },
      { id: "unarmored-defense", name: "Unarmored Defense", description: "While not wearing armor, base AC is 13 plus any shield bonus.", executablePassiveId: "unarmored-defense", provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Barbarian: Unarmored Defense" } },
      { id: "stones-endurance", name: "Stone's Endurance", description: "Twice per long rest, react after taking damage to reduce it by 1d12 + 2.", executableTriggerId: "stones-endurance", provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Goliath: Giant Ancestry (Stone's Endurance)" } },
      { name: "Savage Attacker", description: "Once per turn on a weapon hit, roll the weapon damage dice twice and use either result. The optional reroll is not implemented yet." },
      { name: "Large Form", description: "Once per long rest, become Large for 10 minutes. Size-changing effects are not implemented yet." },
    ],
  },
  source: { format: "flattened-pdf", fileName: "Goliath Barbarian.pdf", importedAt },
};

export const irvenWeber: Character = {
  id: "irven-weber",
  name: "Irven Weber",
  className: "Paladin",
  level: 1,
  rulesetId: "dnd-2024",
  armorClass: 18,
  speedFeet: 30,
  hitPoints: { current: 12, maximum: 12 },
  proficiencyBonus: 2,
  abilities: { strength: 15, dexterity: 10, constitution: 15, intelligence: 8, wisdom: 13, charisma: 14 },
  savingThrowModifiers: { strength: 2, dexterity: 0, constitution: 2, intelligence: -1, wisdom: 3, charisma: 4 },
  resources: [
    { id: "lay-on-hands", name: "Lay On Hands: Healing Pool", kind: "generic", current: 5, maximum: 5, recovery: "long-rest" },
    { id: "spell-slot-1", name: "Level 1 Spell Slots", kind: "spell-slot", level: 1, current: 2, maximum: 2, recovery: "long-rest" },
    { id: "magic-initiate-free-cast", name: "Magic Initiate Free Cast", kind: "generic", current: 1, maximum: 1, recovery: "long-rest" },
  ],
  featureActions: [{
    id: "lay-on-hands",
    name: "Lay On Hands",
    cost: "bonus-action",
    description: "As a Bonus Action, touch yourself or an ally and choose how many Lay On Hands points to spend as Hit Point healing.",
    resourceName: "Lay On Hands: Healing Pool",
    resourceCost: "variable",
    resolution: { type: "healing-pool", rangeFeet: 5 },
    missingCapabilities: ["Poisoned-condition removal is not executable yet."],
    provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Paladin: Lay On Hands" },
  }],
  attacks: [
    { id: "longsword", name: "Longsword", kind: "melee", attackBonus: 4, damage: "1d8 + 2 slashing", normalRangeFeet: 5, description: "Martial, versatile, Sap; one-handed damage.", mastery: "sap" },
    { id: "quarterstaff", name: "Quarterstaff", kind: "melee", attackBonus: 4, damage: "1d6 + 2 bludgeoning", normalRangeFeet: 5, description: "Simple, versatile, Topple; one-handed damage." },
    { id: "javelin", name: "Javelin", kind: "melee", attackBonus: 4, damage: "1d6 + 2 piercing", normalRangeFeet: 5, description: "Simple, thrown, Slow.", mastery: "slow" },
    { id: "thrown-javelin", name: "Thrown Javelin", kind: "ranged", attackBonus: 4, damage: "1d6 + 2 piercing", normalRangeFeet: 30, longRangeFeet: 120, description: "Normal to 30 feet; disadvantage from 35 to 120 feet. Slow.", mastery: "slow" },
    { id: "unarmed-strike", name: "Unarmed Strike", kind: "melee", attackBonus: 4, damage: "3 bludgeoning", normalRangeFeet: 5, description: "Fixed damage shown on the source sheet." },
  ],
  spells: [
    { id: "create-bonfire", name: "Create Bonfire", level: 0, castingTime: "action", rangeFeet: 60, target: "self", targetSide: "hostile", requiresLineOfSight: true, concentration: true, durationRounds: 10, damage: "1d8 fire", save: { ability: "dexterity", dc: 12, damageOnSuccess: "none" }, description: "Creates a damaging bonfire in a 5-foot cube for up to 1 minute.", unsupportedReason: "Persistent area placement and repeat saves are not implemented yet." },
    { id: "control-flames", name: "Control Flames", level: 0, castingTime: "action", rangeFeet: 60, target: "self", requiresLineOfSight: true, description: "Manipulates nonmagical flame in a 5-foot cube.", unsupportedReason: "Environmental flame selection and adjudication are not implemented yet." },
    { id: "searing-smite", name: "Searing Smite", level: 1, castingTime: "bonus-action", rangeFeet: 0, target: "self", requiresLineOfSight: false, trigger: "after-melee-hit", triggeredDamage: "1d6 fire", durationRounds: 10, description: "Immediately after a melee weapon or Unarmed Strike hit, deal extra fire damage and ignite the target until it succeeds on a Constitution save.", effect: { name: "Searing Smite", description: "At the start of each turn, the target takes 1d6 fire damage and then makes a DC 12 Constitution save, ending the spell on a success.", turnStartDamage: "1d6 fire", turnStartSave: { ability: "constitution", dc: 12, endsOnSuccess: true } }, provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Searing Smite" } },
    { id: "heroism", name: "Heroism", level: 1, castingTime: "action", rangeFeet: 5, target: "self-or-single", targetSide: "friendly", requiresLineOfSight: true, concentration: true, durationRounds: 10, description: "A willing creature is immune to the Frightened condition and gains temporary hit points at the start of each turn.", effect: { name: "Heroism", description: "The target is immune to Frightened and gains 2 temporary hit points at the start of each turn.", applyTo: "target", modifiers: { conditionImmunities: ["frightened"] }, turnStartTemporaryHitPoints: 2 }, provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Heroism" } },
    { id: "burning-hands", name: "Burning Hands", level: 1, castingTime: "action", rangeFeet: 0, target: "self", targetSide: "hostile", requiresLineOfSight: false, damage: "3d6 fire", save: { ability: "dexterity", dc: 12, damageOnSuccess: "half" }, description: "Creatures in a 15-foot cone make a Dexterity save; this Magic Initiate spell has one free cast per long rest.", unsupportedReason: "Cone targeting and the free-cast-or-slot resource choice are not implemented yet." },
  ],
  actions: standardActions2024,
  profile: {
    playerName: "ChefdeStruct",
    species: "Human",
    background: "Sage",
    initiativeModifier: 0,
    spellcasting: { ability: "charisma", saveDc: 12, attackBonus: 4 },
    senses: { passivePerception: 11, passiveInsight: 13, passiveInvestigation: 9 },
    skills: { Acrobatics: 0, "Animal Handling": 1, Arcana: 1, Athletics: 2, Deception: 2, History: 1, Insight: 3, Intimidation: 2, Investigation: -1, Medicine: 1, Nature: -1, Perception: 1, Performance: 2, Persuasion: 2, Religion: 1, "Sleight of Hand": 0, Stealth: 0, Survival: 1 },
    proficiencies: { armor: ["Heavy Armor", "Light Armor", "Medium Armor", "Shields"], weapons: ["Martial Weapons", "Simple Weapons"], tools: ["Calligrapher's Supplies"], languages: ["Common", "Draconic"] },
    equipment: [{ name: "Shield", quantity: 1, weightPounds: 6 }, { name: "Chain Mail", quantity: 1, weightPounds: 55 }, { name: "Longsword", quantity: 1, weightPounds: 3 }, { name: "Javelin", quantity: 6, weightPounds: 2 }, { name: "Quarterstaff", quantity: 1, weightPounds: 4 }],
    features: [
      { id: "lay-on-hands", name: "Lay On Hands", description: "Spend points from a 5-point pool as a Bonus Action to heal by touch, or spend 5 points to remove Poisoned.", executableActionId: "lay-on-hands", provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Paladin: Lay On Hands" } },
      { name: "Magic Initiate (Wizard)", description: "Knows two wizard cantrips and Burning Hands, which can be cast once free per long rest or with spell slots." },
      { id: "javelin-mastery-slow", name: "Javelin Mastery (Slow)", description: "After a damaging javelin hit, choose whether to reduce the target's Speed by 10 feet until the start of the next turn.", executableAttackIds: ["javelin", "thrown-javelin"], provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Weapon Mastery: Slow" } },
      { id: "longsword-mastery-sap", name: "Longsword Mastery (Sap)", description: "A longsword hit gives the target disadvantage on its next attack before the start of the next turn.", executableAttackIds: ["longsword"], provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Weapon Mastery: Sap" } },
    ],
  },
  source: { format: "flattened-pdf", fileName: "Human Claric.pdf", importedAt },
};

export const pharos: Character = {
  id: "pharos",
  name: "Pharos",
  className: "Warlock",
  level: 1,
  rulesetId: "dnd-2014",
  armorClass: 12,
  speedFeet: 30,
  hitPoints: { current: 10, maximum: 10 },
  proficiencyBonus: 2,
  abilities: { strength: 8, dexterity: 13, constitution: 15, intelligence: 12, wisdom: 10, charisma: 17 },
  savingThrowModifiers: { strength: -1, dexterity: 1, constitution: 2, intelligence: 1, wisdom: 2, charisma: 5 },
  resources: [
    { id: "spell-slot-1", name: "Level 1 Pact Slot", kind: "spell-slot", level: 1, current: 1, maximum: 1, recovery: "short-rest" },
    { id: "adrenaline-rush", name: "Adrenaline Rush", kind: "generic", current: 2, maximum: 2, recovery: "short-rest" },
    { id: "relentless-endurance", name: "Relentless Endurance", kind: "generic", current: 1, maximum: 1, recovery: "long-rest" },
    { id: "honeyed-words", name: "Honeyed Words", kind: "generic", current: 1, maximum: 1, recovery: "long-rest" },
  ],
  featureActions: [{
    id: "adrenaline-rush",
    name: "Adrenaline Rush",
    cost: "bonus-action",
    description: "Dash as a Bonus Action, gain temporary hit points equal to proficiency bonus, and spend one use.",
    resourceName: "Adrenaline Rush",
    resourceCost: 1,
    resolution: { type: "dash-and-temporary-hit-points", temporaryHitPoints: "proficiency-bonus" },
    provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Orc: Adrenaline Rush" },
  }],
  triggeredFeatures: [{
    id: "dark-ones-blessing",
    name: "Dark One's Blessing",
    trigger: "reduces-hostile-to-zero-hit-points",
    optional: false,
    description: "After reducing a hostile creature to 0 Hit Points, gain 4 temporary Hit Points.",
    resolution: { type: "gain-temporary-hit-points", amount: 4 },
    provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Fiend Patron: Dark One's Blessing" },
  }, {
    id: "relentless-endurance",
    name: "Relentless Endurance",
    trigger: "reduced-to-zero-hit-points",
    optional: true,
    description: "When reduced to 0 HP but not killed outright, choose to drop to 1 HP instead and spend one use.",
    resourceName: "Relentless Endurance",
    resourceCost: 1,
    resolution: { type: "drop-to-one-hit-point" },
    provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Orc: Relentless Endurance" },
  }],
  attacks: [
    { id: "club", name: "Club", kind: "melee", attackBonus: 1, damage: "1d4 - 1 bludgeoning", normalRangeFeet: 5, description: "Simple, light, Slow." },
    { id: "light-crossbow", name: "Light Crossbow", kind: "ranged", attackBonus: 3, damage: "1d8 + 1 piercing", normalRangeFeet: 80, longRangeFeet: 320, description: "Simple, ammunition, loading, two-handed, Slow." },
    { id: "dagger", name: "Dagger", kind: "melee", attackBonus: 3, damage: "1d4 + 1 piercing", normalRangeFeet: 5, description: "Simple, finesse, light, Nick." },
    { id: "thrown-dagger", name: "Thrown Dagger", kind: "ranged", attackBonus: 3, damage: "1d4 + 1 piercing", normalRangeFeet: 20, longRangeFeet: 60, description: "Normal to 20 feet; disadvantage from 25 to 60 feet." },
    { id: "unarmed-strike", name: "Unarmed Strike", kind: "melee", attackBonus: 1, damage: "0 bludgeoning", normalRangeFeet: 5, description: "Fixed damage shown on the source sheet." },
  ],
  spells: [
    { id: "chill-touch", name: "Chill Touch", level: 0, castingTime: "action", rangeFeet: 120, target: "single", targetSide: "hostile", requiresLineOfSight: true, attackBonus: 5, damage: "1d8 necrotic", durationRounds: 1, description: "A ranged spell attack deals necrotic damage and prevents healing until the start of the caster's next turn. An undead target also has disadvantage on attacks against the caster until the end of the caster's next turn.", onHitEffect: { preventsHealing: true, undeadTargetDisadvantageAgainstCaster: true }, provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Chill Touch" } },
    { id: "true-strike", name: "True Strike", level: 0, castingTime: "action", rangeFeet: 30, target: "single", targetSide: "hostile", requiresLineOfSight: true, concentration: true, durationRounds: 1, description: "On the caster's next turn, the first attack roll against the chosen target has advantage.", effect: { name: "True Strike", description: "Advantage on the first attack roll against the chosen target on the caster's next turn.", applyTo: "caster", attackTarget: "spell-target", starts: "start-of-caster-next-turn", expires: "end-of-caster-next-turn", modifiers: { outgoingAttacks: "advantage" }, consumeOnAttackRoll: true }, provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, True Strike" } },
    { id: "druidcraft", name: "Druidcraft", level: 0, castingTime: "action", rangeFeet: 30, target: "self", requiresLineOfSight: true, description: "Creates a minor nature effect.", unsupportedReason: "Environmental utility-spell adjudication is not implemented yet." },
    { id: "guidance", name: "Guidance", level: 0, castingTime: "action", rangeFeet: 5, target: "self-or-single", targetSide: "friendly", requiresLineOfSight: true, concentration: true, durationRounds: 10, description: "A touched creature can add 1d4 to one ability check.", unsupportedReason: "Ability-check prompts and the optional d4 bonus are not implemented yet." },
    { id: "expeditious-retreat", name: "Expeditious Retreat", level: 1, castingTime: "bonus-action", rangeFeet: 0, target: "self", requiresLineOfSight: false, concentration: true, durationRounds: 100, description: "Dash when cast, then Dash as a Bonus Action on each turn while concentration lasts.", effect: { name: "Expeditious Retreat", description: "The caster can take the Dash action as a Bonus Action until concentration ends.", applyTo: "caster", modifiers: { bonusActionDash: true }, dashOnCast: true }, provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Expeditious Retreat" } },
    { id: "charm-person", name: "Charm Person", level: 1, castingTime: "action", rangeFeet: 30, target: "single", targetSide: "hostile", requiresLineOfSight: true, save: { ability: "wisdom", dc: 13, damageOnSuccess: "none" }, targetCreatureTypes: ["humanoid"], hostileSaveAdvantage: true, durationRounds: 600, description: "A humanoid target makes a DC 13 Wisdom save with advantage while fighting the caster or an ally. On a failure, it is charmed for 1 hour or until harmed by the caster or an ally.", effect: { name: "Charm Person", description: "The target is charmed by the caster and cannot harm the caster until the spell ends.", conditionGranted: "charmed", modifiers: { preventsHarmingSource: true }, endsWhenSourceHarmsTarget: true }, provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Charm Person" } },
  ],
  actions: standardActions2014,
  profile: {
    playerName: "ChefdeStruct",
    species: "Orc",
    background: "Pact Seeker",
    initiativeModifier: 1,
    spellcasting: { ability: "charisma", saveDc: 13, attackBonus: 5 },
    senses: { darkvisionFeet: 120, passivePerception: 10, passiveInsight: 10, passiveInvestigation: 13 },
    skills: { Acrobatics: 1, "Animal Handling": 0, Arcana: 3, Athletics: -1, Deception: 3, History: 1, Insight: 0, Intimidation: 5, Investigation: 3, Medicine: 0, Nature: 3, Perception: 0, Performance: 3, Persuasion: 5, Religion: 1, "Sleight of Hand": 1, Stealth: 1, Survival: 0 },
    proficiencies: { armor: ["Light Armor"], weapons: ["Simple Weapons"], tools: ["Calligrapher's Supplies"], languages: ["Alzhedo", "Common", "Giant", "Sylvan"] },
    equipment: [{ name: "Leather Armor", quantity: 1, weightPounds: 10 }, { name: "Dagger", quantity: 2, weightPounds: 1 }, { name: "Club", quantity: 1, weightPounds: 2 }, { name: "Light Crossbow", quantity: 1, weightPounds: 5 }, { name: "Crossbow Bolts", quantity: 20, weightPounds: 0.075 }],
    features: [
      { id: "dark-ones-blessing", name: "Dark One's Blessing", description: "Gain 4 temporary hit points after reducing a hostile creature to 0 HP.", executableTriggerId: "dark-ones-blessing", provenance: { rulesetId: "dnd-2014", sourceId: "srd-5.1", sourceReference: "SRD 5.1, Fiend Patron: Dark One's Blessing" } },
      { id: "adrenaline-rush", name: "Adrenaline Rush", description: "Twice per short or long rest, Dash as a bonus action and gain 2 temporary hit points.", executableActionId: "adrenaline-rush", provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Orc: Adrenaline Rush" } },
      { id: "relentless-endurance", name: "Relentless Endurance", description: "Once per long rest, choose to drop to 1 HP instead of 0 when reduced to 0 HP but not killed outright.", executableTriggerId: "relentless-endurance", provenance: { rulesetId: "dnd-2024", sourceId: "srd-5.2.1", sourceReference: "SRD 5.2.1, Orc: Relentless Endurance" } },
      { name: "Honeyed Words", description: "Reroll a failed Deception or Persuasion check; the resource is spent only when it changes failure to success. Skill-check rerolls are not implemented yet." },
    ],
  },
  source: { format: "flattened-pdf", fileName: "Orc Warlock.pdf", importedAt },
};

export const VERIFIED_PDF_CHARACTERS: Character[] = [surinaDaardendrian, goliathBarbarian, irvenWeber, pharos];
