import type { RuleSource, RuleSourceId } from "./types";

export const RULE_SOURCES: Record<RuleSourceId, RuleSource> = {
  "srd-5.1": {
    id: "srd-5.1",
    name: "System Reference Document 5.1",
    version: "5.1",
    authority: "official",
    rulesetIds: ["dnd-2014"],
    license: "CC-BY-4.0",
    url: "https://www.dndbeyond.com/resources/1781-systems-reference-document-srd",
    attribution: "Dungeons & Dragons SRD 5.1 by Wizards of the Coast LLC, licensed under CC BY 4.0.",
    validationRequired: false,
  },
  "srd-5.2.1": {
    id: "srd-5.2.1",
    name: "System Reference Document 5.2.1",
    version: "5.2.1",
    authority: "official",
    rulesetIds: ["dnd-2024"],
    license: "CC-BY-4.0",
    url: "https://www.dndbeyond.com/srd",
    attribution: "Dungeons & Dragons SRD 5.2.1 by Wizards of the Coast LLC, licensed under CC BY 4.0.",
    validationRequired: false,
  },
  "official-errata": {
    id: "official-errata",
    name: "Official errata and rules clarifications",
    version: "rolling",
    authority: "official",
    rulesetIds: ["dnd-2014", "dnd-2024"],
    license: "CC-BY-4.0",
    url: "https://www.dndbeyond.com/sources/dnd/sac/sage-advice-compendium",
    validationRequired: false,
  },
  "open5e-v2": {
    id: "open5e-v2",
    name: "Open5e API V2",
    version: "v2",
    authority: "community-index",
    rulesetIds: ["dnd-2014", "dnd-2024"],
    license: "CC-BY-4.0",
    url: "https://open5e.com/api-docs",
    validationRequired: true,
  },
  "user-imported": {
    id: "user-imported",
    name: "User-imported character sheet",
    version: "per-upload",
    authority: "user",
    rulesetIds: ["dnd-2014", "dnd-2024"],
    license: "user-provided",
    validationRequired: true,
  },
  "adam-original": {
    id: "adam-original",
    name: "ADaM original content",
    version: "current",
    authority: "adam",
    rulesetIds: ["dnd-2014", "dnd-2024"],
    license: "internal",
    validationRequired: false,
  },
};
